development:
  adapter: postgresql
  encoding: unicode
  database: civet_dev
  pool: 5
  username: rails
  password: '!QAZxsw2#EDC'

test:
  adapter: postgresql
  encoding: unicode
  database: civet_test
  pool: 5
  username: rails
  password: '!QAZxsw2#EDC'

production:
  adapter: postgresql
  encoding: unicode
  database: civet_production
  pool: 5
  username: rails
  password: '!QAZxsw2#EDC'
